### ISSUE TITLE
第一次启动报错themeItems

### ISSUE THREAD

**Issue by mianba** [ivarptr/yu-writer.site#246]
Uncaught Exception:
TypeError: Cannot read property 'themeItems' of undefined
    at e.exports.createMainWindow (/Applications/Yu Writer.app/Contents/Resources/app/src/script/mainprocess.js:1:6766)
    at App.h.on (/Applications/Yu Writer.app/Contents/Resources/app/src/script/mainprocess.js:1:21650)
    at emitTwo (events.js:125:13)
    at App.emit (events.js:213:7)

**Comment by hemashushu** [comment]
@mianba 新版本 0.5 已释出，理论上应该解决了这个问题，欢迎下载试用看看问题是否依旧，如有问题欢迎随时问，这个 issue 我先关闭哈。
