### ISSUE TITLE
部分md尝试双击打开时卡死,重启后js报错

### ISSUE THREAD

**Issue by shulin-li** [ivarptr/yu-writer.site#326]
一个很小的md文件(6KB),但是打开时卡死。。。。其他的都没问题 ,结束掉进程后,双击其他md文件JS报错
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
    at e.exports.sendByWindow (D:\YU-Writer\yu-writer-beta-0.5.2-windows-x64\Yu Writer\resources\app.asar\src\script\mainprocess.js:1:29511)
    at getFileItemParentFolder (D:\YU-Writer\yu-writer-beta-0.5.2-windows-x64\Yu Writer\resources\app.asar\src\script\mainprocess.js:1:86091)
    at localLibrary.getFileItemByFilePath (D:\YU-Writer\yu-writer-beta-0.5.2-windows-x64\Yu Writer\resources\app.asar\src\script\mainprocess.js:1:101314)
    at f.readFile (D:\YU-Writer\yu-writer-beta-0.5.2-windows-x64\Yu Writer\resources\app.asar\src\script\mainprocess.js:1:61807)
    at i.readFile (D:\YU-Writer\yu-writer-beta-0.5.2-windows-x64\Yu Writer\resources\app.asar\src\script\mainprocess.js:1:143608)
    at tryToString (fs.js:513:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)

[确定]

**Comment by shulin-li** [comment]
更加神奇的是,我重新解压了一遍yu writer,
然后在yu writer内新建文档,使用其他markdown编辑器打开在yu writer内卡死的那个md文件,尝试将内容复制到yu writer内的新建文档里,程序再次直接卡死。。。。

**Comment by hemashushu** [comment]
看提示似乎是程序卡死后没有完全退出，主窗口关闭了但线程还在。看来关键是这个 md 文件有令程序卡死的内容。如果方便的话，是否可寄一份样本给我（email: hippospark@gmail.com），我分析一下是什么原因，非常感谢

**Comment by shulin-li** [comment]
已经发送了,不过个人感觉应该不是md文件的问题,我后来还是采取"将内容复制到Yu Writer内的新建文档"的方式,不过是一小段一小段复制的(之前说的卡死是尝试直接全文复制),最后没有出现问题。。。。

**Comment by hemashushu** [comment]
@shulin-li 文档已收到，我迟些时候排查一下，或者先试试目前最新版本 0.5.3，上一个版本因为很多异常都没捕捉所以经常弹出错误，试试新版本它的错误信息是什么。感谢反馈！

**Comment by shulin-li** [comment]
0.5.3使用:尝试直接打开"异常文档"时,仍然卡死;
尝试"一次性复制时"仍然卡死;
卡死后结束进程,重新打开Yu Writer,打开其他md文件,无报错信息。
补充:0.5.2和0.5.3在尝试打开"异常文档"卡死时,CPU占用率由卡死前的0.X%升到20%左右。

**Comment by hemashushu** [comment]
@shulin-li 原因已经找到，是因为 ```xml 那段代码引起的。

如果把 ```xml 以及 ``` 这两行后面的两个空格（共4个空格）删掉，文档不会卡死。

所以原因大概是：当正文包含那段代码时，引起语法解析器的死循环，所以就卡死了。之所以把那四个空格删除就正常，那是因为删除后尾的空格后该部分文本被解析为代码块，因为代码块目前还没进行语法解析和高亮，所以就刚好避开正文的语法解析了。

所以暂时的解决方法是在代码块的首行和末行不加上空格即可。

我这边会找一下是什么文本导致语法解析器死循环。谢谢你的反馈和提供的样本！
