### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by oliwill** [ivarptr/yu-writer.site#48]
当前版本 V0.4.0
系统版本：macOS Sierra 10.12.6

`
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/Users/al/Library/Caches/Yu Writer/fileinfo/index.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at h.updateFileInfoItems (/Applications/Yu Writer.app/Contents/Resources/app/src/script/mainprocess.js:1:38665)
    at h.update (/Applications/Yu Writer.app/Contents/Resources/app/src/script/mainprocess.js:1:39611)
    at P.updateFile (/Applications/Yu Writer.app/Contents/Resources/app/src/script/mainprocess.js:1:65187)
    at EventEmitter.messageServer.addEventListener.e (/Applications/Yu Writer.app/Contents/Resources/app/src/script/mainprocess.js:1:79852)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at l.dispatch (/Applications/Yu Writer.app/Contents/Resources/app/src/script/mainprocess.js:1:88500)
<img width="420" alt="wx20170903-140815 2x" src="https://user-images.githubusercontent.com/15229320/30000968-5e40f806-90b1-11e7-8c9e-b8cbe4fd9bf1.png">
`

**Comment by hemashushu** [comment]
@oliwill 感谢反馈！

**Comment by mixj93** [comment]
类似的问题：
```
Uncaught Exception:
TypeError: Cannot read property 'themeItems' of undefined
    at G.createMainWindow (/Applications/Yu Writer.app/Contents/Resources/app.asar/src/script/mainprocess.js:1:4990)
    at App.d.on (/Applications/Yu Writer.app/Contents/Resources/app.asar/src/script/mainprocess.js:1:16336)
    at emitTwo (events.js:106:13)
    at App.emit (events.js:194:7)
```

版本：Yu Writer Beta 0.4.4
系统：macOS Sierra 10.12.6

**Comment by hemashushu** [comment]
@oliwill @mixj93 新版本 0.5 已释出，理论上应该解决了这个问题，欢迎下载试用看看问题是否依旧，如有问题欢迎随时问，这个 issue 我先关闭哈。
