### ISSUE TITLE
打开失败了

### ISSUE THREAD

**Issue by gnaixx** [ivarptr/yu-writer.site#93]
version: Beta 0.4.4
mac: OS X EI Capitan 10.11.6

log:
**A JavaScript error occurred in the main process**
```
Uncaught Exception:
TypeError: Cannot read property 'themeItems' of undefined
    at G.createMainWindow (/Applications/Yu Writer.app/Contents/Resources/app.asar/src/script/mainprocess.js:1:4990)
    at App.d.on (/Applications/Yu Writer.app/Contents/Resources/app.asar/src/script/mainprocess.js:1:16336)
    at emitTwo (events.js:106:13)
    at App.emit (events.js:194:7)
```

alpha 0.3.1 is ok

**Comment by hemashushu** [comment]
@gnaixx 这个我暂时也不太清楚是什么原因，或者试试手动清空一下 Yu Writer 的缓存，位置位于 `~/Library/Application Support/Yu Writer` 把整个文件夹删掉即可。

**Comment by gnaixx** [comment]
@ivarptr 我是第一安装就打不开了 应该还没有缓存

**Comment by hemashushu** [comment]
好的，我仔细检查一下

**Comment by hemashushu** [comment]
@gnaixx 新版本 0.5.3 已释出，理论上已经解决了这个问题，欢迎下载试用看看问题是否依旧，如有问题欢迎随时问，这个 issue 我先关闭哈。
